### ISSUE TITLE
Graceful restart is dead since 1.6.20

### ISSUE THREAD

**Issue by jonathandhn** [litespeedtech/openlitespeed#231]
Ubuntu 20.04, Centos 8, 

Since 1.6.20 adminlistener is not working anymore at graceful restart, nor reload, nor full reload, it must be stoped wait start twice. 
```
2021-04-06 15:40:15.649426 [NOTICE] [64136] [REDACTED:HTTP2-11#_AdminVHost] [STDERR] PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /usr/local/lsws/admin/html.open/lib/ControllerBase.php on line 507
2021-04-06 15:40:15.650492 [NOTICE] [64136] [REDACTED:HTTP2-11#_AdminVHost] [STDERR] cmd restart
 failed to connect to server! socket_connect() failed: Unknown server error 
```

**Comment by peterlh** [comment]
+1 Same issue here on ubuntu 18.04LTS

**Comment by jonathandhn** [comment]
```
2021-04-06 17:19:32.008204 | ERROR | [55382] HttpListener::start(): Can't listen at address adminListener: Address already in use!
-- | -- | --
2021-04-06 17:19:32.008264 | ERROR | [55382] HttpServer::addListener(adminListener) failed to create new listener
2021-04-06 17:19:32.008271 | ERROR | [55382] [config:admin:listener:adminListener] failed to start listener on address *:7080!
2021-04-06 17:19:32.008277 | ERROR | [55382] [config:admin:listener] No listener is available for admin virtual host!
2021-04-06 17:19:32.008500 | ERROR | [55382] Fatal error in configuration, exit!

```

**Comment by jonathandhn** [comment]
```
systemctl status openlitespeed
● lshttpd.service - OpenLiteSpeed HTTP Server
     Loaded: loaded (/etc/systemd/system/lshttpd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-04-06 17:19:34 CEST; 7min ago
    Process: 55363 ExecStart=/usr/local/lsws/bin/lswsctrl start (code=exited, status=0/SUCCESS)
    Process: 55576 ExecReload=/usr/local/lsws/bin/lswsctrl restart (code=exited, status=0/SUCCESS)
   Main PID: 55590 (litespeed)
     CGroup: /system.slice/lshttpd.service
             ├─55405 openlitespeed (lshttpd - main)
             ├─55408 openlitespeed (lscgid)
             ├─55409 openlitespeed (lshttpd - #01)
             ├─55560 admin_php
             ├─55590 openlitespeed (lshttpd - main)
             ├─55591 openlitespeed (lscgid)
             ├─55592 openlitespeed (lshttpd - #01)
             ├─55593 openlitespeed (lshttpd - #02)
             ├─55594 lsphp
             └─55595 lsphp

Apr 06 17:19:31 vps-ce3a2caa systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 06 17:19:31 vps-ce3a2caa systemd[1]: lshttpd.service: Found left-over process 55101 (litespeed) in control group while starting unit. Ignoring.
Apr 06 17:19:31 vps-ce3a2caa systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 06 17:19:31 vps-ce3a2caa systemd[1]: Starting OpenLiteSpeed HTTP Server...
Apr 06 17:19:31 vps-ce3a2caa lswsctrl[55363]: [OK] litespeed: pid=55382.

```

**Comment by litespeedtech** [comment]
This bug has been fixed last night, a new build of 1.6.21 and 1.7.10 have been pushed today.
Use package system or lsup.sh to update.
Should be fixed.

**Comment by peterlh** [comment]
updated 2 servers, can confirm that restart from adminpanel works again

**Comment by litespeedtech** [comment]
If still have problem, please reopen this issue.

**Comment by demyxco** [comment]
I'm still getting this same error on 1.6.21 and 1.7.11. Anything I can submit to further diagnose? OLS has been installed via binary install and upgraded/downgraded using lsup.sh.

```
2021-06-21 22:53:50.279219 [NOTICE] [19589] [73.90.218.20:49770:HTTP2-59#_AdminVHost] [STDERR] PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /usr/local/lsws/admin/html.open/lib/ControllerBase.php on line 507
2021-06-21 22:53:50.279511 [NOTICE] [19589] [73.90.218.20:49770:HTTP2-59#_AdminVHost] [STDERR] cmd restart
 failed to connect to server! socket_connect() failed: Unknown server error
```

**Comment by demyxco** [comment]
My fix was the directory `/usr/local/lsws/admin/tmp` needed to be emptied out and then `service lshttpd restart`. Thanks for the help Lauren!

**Comment by doonfrs** [comment]
I still face the same problem from time to time after graceful restart.
