### ISSUE TITLE
chrome HTTP/3 connection timeout issue for long-running scripts and other issues

### ISSUE THREAD

**Issue by ashish168527** [litespeedtech/openlitespeed#255]
I'm facing these issues on my server which was fixed in this lightspeed latest release please fix these on this project as well as soon as possible:

LSWS 6.0.4
(06-30-2021)
Bugfixes
BUGFIX Address a chrome HTTP/3 connection timeout issue for long-running scripts.
BUGFIX Address a multi-thread race condition in mod_security engine.
BUGFIX Detect dead HTTP/2 connections during server cool-down.
BUGFIX Improve request/response header name validation to avoid HTTP/2 and HTTP/3 protocol violations.

thanks

**Comment by litespeedtech** [comment]
It has been fixed in upcoming 1.7.12 release. 
You can try the pre-built binary with
 
/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.12

**Comment by ashish168527** [comment]
okay thanks, @litespeedtech for the super-fast response,  when are you guys planning to launch this officially?

**Comment by litespeedtech** [comment]
Yes, will be in this week.

**Comment by ashish168527** [comment]
okay, thanks @litespeedtech

**Comment by ashish168527** [comment]
@litespeedtech connection timeout issue is still occurring  even after this /usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.12 as well

**Comment by litespeedtech** [comment]
It is likely a different issue. For long run script, you can take a look 
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:run-without-timeouts
It apply to OLS as well.

**Comment by litespeedtech** [comment]
Release 1.7.12 is available.

**Comment by ashish168527** [comment]
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:run-without-timeouts
tried to use this as well but that didn't worked then I noticed after restarting the server after few minutes around 15 or more than that lightspeed stops responding and that's causing the timeout issue so I used a cron job to restart it every 15 minutes I'm using this as a temporary solution right now.

**Comment by litespeedtech** [comment]
Does it stop serving PHP script, or stop serving everything, include static files? 
It is better to generate some debug logging when it happens, we can check what is the root cause.

**Comment by ashish168527** [comment]
I just checked after updating it stop's serving PHP I just tried to access the static images of the page it's loading and I'm getting this Cloudflare error while loading website "Error 522 Connection timed out"

**Comment by ashish168527** [comment]
and generally, my CPU uses are around 60-100% after this thing it goes to 0-3%

**Comment by litespeedtech** [comment]
Do you have request rate throttling enabled? 
If you use cloudflare, you need to config 
https://openlitespeed.org/kb/show-real-visitor-ip-instead-of-cloudflare-ips/
If you would like to have our staff to take look what is going on, you can email to bug {at} litespeedtech.com

**Comment by ashish168527** [comment]
this is in lightspeed log

<html>
<body>


Time | Level | Message
-- | -- | --
2021-07-10 11:02:54.024386 | NOTICE | [79687] sendKillCmdToWatchdog: 'extappkill:193972:-3:0'.
2021-07-10 11:02:54.200378 | NOTICE | [79679] Cmd from child: [extappkill:193972:-3:0]
2021-07-10 11:03:25.404056 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:03:25.404099 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:03:25.404492 | NOTICE | [79687] [AdminPHP] add child process pid: 194398
2021-07-10 11:03:56.031668 | NOTICE | [79687] sendKillCmdToWatchdog: 'extappkill:194398:-3:0'.
2021-07-10 11:03:56.200345 | NOTICE | [79679] Cmd from child: [extappkill:194398:-3:0]
2021-07-10 11:04:26.573125 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:04:26.573175 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:04:26.573554 | NOTICE | [79687] [AdminPHP] add child process pid: 194821
2021-07-10 11:05:04.086525 | NOTICE | [79687] sendKillCmdToWatchdog: 'extappkill:194821:-3:0'.
2021-07-10 11:05:04.200287 | NOTICE | [79679] Cmd from child: [extappkill:194821:-3:0]
2021-07-10 11:05:30.263275 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:05:30.263315 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:05:30.263697 | NOTICE | [79687] [AdminPHP] add child process pid: 195255
2021-07-10 11:06:01.051587 | NOTICE | [79687] sendKillCmdToWatchdog: 'extappkill:195255:-3:0'.
2021-07-10 11:06:01.200415 | NOTICE | [79679] Cmd from child: [extappkill:195255:-3:0]
2021-07-10 11:06:32.175923 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:06:32.175960 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:06:32.176369 | NOTICE | [79687] [AdminPHP] add child process pid: 195696
2021-07-10 11:07:03.012292 | NOTICE | [79687] sendKillCmdToWatchdog: 'extappkill:195696:-3:0'.
2021-07-10 11:07:03.200389 | NOTICE | [79679] Cmd from child: [extappkill:195696:-3:0]
2021-07-10 11:07:19.594507 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:07:19.594556 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:07:19.594931 | NOTICE | [79687] [AdminPHP] add child process pid: 196022
2021-07-10 11:07:25.038412 | NOTICE | [79687] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 99 setuidmode 2.
2021-07-10 11:07:25.038452 | NOTICE | [79687] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 99, flags: 0.
2021-07-10 11:07:25.038832 | NOTICE | [79687] [AdminPHP] add child process pid: 196062


</body>
</html>

**Comment by ashish168527** [comment]
I upgraded to the latest release 1.7.12 and removed my site from Cloudflare for 3 hours just to test, it worked fine without any issue, then I switched back to Cloudflare, and within 30-40 minutes lightspeed stopped responding to the requests and the website started giving the "Error 522 Connection timed out" Cloudflare,

already placed this to my .htaccess of the site

<IfModule Litespeed>
    RewriteEngine On
    RewriteRule .* - [E=noabort:1, E=noconntimeout:1]
</IfModule>


already placed the Cloudflare IP list to allow in Server Configuration > Security (lightspeed:7080) settings

Access Control >

Allowed List
--
ALL, 173.245.48.0/20T, 103.21.244.0/22T, 103.22.200.0/22T, 103.31.4.0/22T, 141.101.64.0/18T, 108.162.192.0/18T, 190.93.240.0/20T, 188.114.96.0/20T, 197.234.240.0/22T, 198.41.128.0/17T, 162.158.0.0/15T, 172.64.0.0/13T, 131.0.72.0/22T, 104.16.0.0/13T, 104.24.0.0/14T, 2400:cb00::/32T, 2606:4700::/32T, 2803:f800::/32T, 2405:b500::/32T, 2405:8100::/32T, 2a06:98c0::/29T, 2c0f:f248::/32T


Server Configuration > General >
General Settings To =>

Use Client IP in Header  -- | -- Trusted IP Only

Server Configuration > Security (this setting is the default)

Per Client Throttling

Per Client Throttling
Static Requests/second	0
Dynamic Requests/second	0
Outbound Bandwidth (bytes/sec)	0
Inbound Bandwidth (bytes/sec)	0
Connection Soft Limit	10000
Connection Hard Limit	10000
Block Bad Request	Not Set
Grace Period (sec)	15
Banned Period (sec)	300

**Comment by ashish168527** [comment]
Tuning Details ( default config)

Max Connections -10000
Max SSL Connections - 10000
Connection Timeout - 300
Keep Alive Timeout - 5
Cache Size in memory - 20M

**Comment by qtwrk** [comment]
maybe due to this, according to their [doc](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#522error) 

![timeout](https://www.litespeedshare.net/2021/07/0fa200-ScreenShot2021-07-11_04.02.34.png)

**Comment by litespeedtech** [comment]
You can try https://quic.cloud/ instead.

**Comment by ashish168527** [comment]
so far there's no solution I'm gonna continue using the cron job to restart lsws every around 15 minutes to get it running as a temporary solution.

**Comment by ashish168527** [comment]
finally, the last update fixed the timeout issue that I was facing on my server Thanks @litespeedtech
